class ScoringFactor:
    EASY_FACTOR = 4
    MEDIUM_FACTOR = 2
    HARD_FACTOR = 1
    SLOW_FACTOR = 1
    FAST_FACTOR = 2
    LV1_DEFAULT_BALLOT = 0
    FIRST_STAGE_FACTOR = 1
    SECOND_STAGE_FACTOR = 2
    THIRD_STAGE_FACTOR = 4
    FOURTH_STAGE_FACTOR = 8
    HOWLER_FACTOR = 16
